/*
 * Copyright 2024 Zhiyi Zhang for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifdef __WIDL__
#pragma makedep header install winmd
#pragma winrt ns_prefix
#endif

import "inspectable.idl";
import "asyncinfo.idl";
import "eventtoken.idl";
import "windowscontracts.idl";
import "windows.foundation.idl";
import "windows.applicationmodel.idl";
import "windows.applicationmodel.activation.idl";
import "windows.applicationmodel.core.idl";
import "windows.foundation.numerics.idl";
import "windows.graphics.imaging.idl";
import "windows.ui.idl";
import "windows.ui.composition.idl";
import "windows.ui.core.idl";
import "windows.ui.input.idl";
import "windows.ui.xaml.controls.primitives.idl";
import "windows.ui.xaml.interop.idl";

namespace Windows.UI.Xaml {
    typedef enum ApplicationTheme ApplicationTheme;

    interface IApplication;
    interface IApplication2;
    interface IApplication3;
    interface IApplicationFactory;
    interface IApplicationInitializationCallbackParams;
    interface IApplicationOverrides;
    interface IApplicationStatics;
    interface IBindingFailedEventArgs;
    interface IDataTemplateKey;
    interface IDataTemplateKeyFactory;
    interface IDebugSettings;
    interface IDebugSettings2;
    interface IDependencyObject;
    interface IDependencyObject2;
    interface IDependencyObjectFactory;
    interface IDependencyProperty;
    interface IDependencyPropertyChangedEventArgs;
    interface IDependencyPropertyStatics;
    interface IPropertyMetadata;
    interface IPropertyMetadataFactory;
    interface IPropertyMetadataStatics;
    interface IResourceDictionary;
    interface IUnhandledExceptionEventArgs;

    runtimeclass Application;
    runtimeclass ApplicationInitializationCallbackParams;
    runtimeclass BindingFailedEventArgs;
    runtimeclass DataTemplateKey;
    runtimeclass DebugSettings;
    runtimeclass DependencyObject;
    runtimeclass DependencyProperty;
    runtimeclass DependencyPropertyChangedEventArgs;
    runtimeclass PropertyMetadata;
    runtimeclass ResourceDictionary;
    runtimeclass UnhandledExceptionEventArgs;

    declare {
        interface Windows.Foundation.Collections.IKeyValuePair<IInspectable *, IInspectable *>;
        interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<IInspectable *, IInspectable *> *>;
        interface Windows.Foundation.Collections.IIterable<Windows.UI.Xaml.ResourceDictionary *>;
        interface Windows.Foundation.Collections.IIterator<Windows.Foundation.Collections.IKeyValuePair<IInspectable *, IInspectable *> *>;
        interface Windows.Foundation.Collections.IIterator<Windows.UI.Xaml.ResourceDictionary *>;
        interface Windows.Foundation.Collections.IMap<IInspectable *, IInspectable *>;
        interface Windows.Foundation.Collections.IMapView<IInspectable *, IInspectable *>;
        interface Windows.Foundation.Collections.IVector<Windows.UI.Xaml.ResourceDictionary *>;
        interface Windows.Foundation.Collections.IVectorView<Windows.UI.Xaml.ResourceDictionary *>;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(b6351c55-c284-46e4-8310-fb0967fab76f)
    ]
    delegate HRESULT ApplicationInitializationCallback([in] Windows.UI.Xaml.ApplicationInitializationCallbackParams *p);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(136b1782-54ba-420d-a1aa-82828721cde6)
    ]
    delegate HRESULT BindingFailedEventHandler([in] IInspectable *sender, [in] Windows.UI.Xaml.BindingFailedEventArgs *e);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(d6ecb12c-15b5-4ec8-b95c-cdd208f08153)
    ]
    delegate HRESULT CreateDefaultValueCallback([out, retval] IInspectable **result);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(45883d16-27bf-4bc1-ac26-94c1601f3a49)
    ]
    delegate HRESULT DependencyPropertyChangedCallback([in] Windows.UI.Xaml.DependencyObject *sender, [in] Windows.UI.Xaml.DependencyProperty *dp);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(5a9f8a25-d142-44a4-8231-fd676724f29b)
    ]
    delegate HRESULT PropertyChangedCallback([in] Windows.UI.Xaml.DependencyObject *obj, [in] Windows.UI.Xaml.DependencyPropertyChangedEventArgs *args);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(23429465-e36a-40e2-b139-a4704602a6e1)
    ]
    delegate HRESULT SuspendingEventHandler([in] IInspectable *sender, [in] Windows.ApplicationModel.SuspendingEventArgs *e);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(9274e6bd-49a1-4958-beee-d0e19587b6e3)
    ]
    delegate HRESULT UnhandledExceptionEventHandler([in] IInspectable *sender, [in] Windows.UI.Xaml.UnhandledExceptionEventArgs *e);

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum ApplicationTheme
    {
        Light = 0,
        Dark  = 1,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.Application),
        uuid(74b861a1-7487-46a9-9a6e-c78b512726c5)
    ]
    interface IApplication : IInspectable
    {
        [propget] HRESULT Resources([out, retval] Windows.UI.Xaml.ResourceDictionary **value);
        [propput] HRESULT Resources([in] Windows.UI.Xaml.ResourceDictionary *value);
        [propget] HRESULT DebugSettings([out, retval] Windows.UI.Xaml.DebugSettings **value);
        [propget] HRESULT RequestedTheme([out, retval] Windows.UI.Xaml.ApplicationTheme *value);
        [propput] HRESULT RequestedTheme([in] Windows.UI.Xaml.ApplicationTheme value);
        [eventadd] HRESULT UnhandledException([in] Windows.UI.Xaml.UnhandledExceptionEventHandler *handler, [out, retval] EventRegistrationToken *cookie);
        [eventremove] HRESULT UnhandledException([in] EventRegistrationToken cookie);
        [eventadd] HRESULT Suspending([in] Windows.UI.Xaml.SuspendingEventHandler *handler, [out, retval] EventRegistrationToken *cookie);
        [eventremove] HRESULT Suspending([in] EventRegistrationToken cookie);
        [eventadd] HRESULT Resuming([in] Windows.Foundation.EventHandler<IInspectable *> *handler, [out, retval] EventRegistrationToken *cookie);
        [eventremove] HRESULT Resuming([in] EventRegistrationToken cookie);
        HRESULT Exit();
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.Application),
        uuid(93bbe361-be5a-4ee3-b4a3-95118dc97a89)
    ]
    interface IApplicationFactory : IInspectable
    {
        HRESULT CreateInstance([in] IInspectable *base_interface, [out] IInspectable **inner_interface, [out, retval] Windows.UI.Xaml.Application **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.ApplicationInitializationCallbackParams),
        uuid(751b792e-5772-4488-8b87-f547faa64474)
    ]
    interface IApplicationInitializationCallbackParams : IInspectable
    {
    }

//    [
//        contract(Windows.Foundation.UniversalApiContract, 1.0),
//        exclusiveto(Windows.UI.Xaml.Application),
//        uuid(25f99ff7-9347-459a-9fac-b2d0e11c1a0f)
//    ]
//    interface IApplicationOverrides : IInspectable
//    {
//        HRESULT OnActivated([in] Windows.ApplicationModel.Activation.IActivatedEventArgs *args);
//        HRESULT OnLaunched([in] Windows.ApplicationModel.Activation.LaunchActivatedEventArgs *args);
//        HRESULT OnFileActivated([in] Windows.ApplicationModel.Activation.FileActivatedEventArgs *args);
//        HRESULT OnSearchActivated([in] Windows.ApplicationModel.Activation.SearchActivatedEventArgs *args);
//        HRESULT OnShareTargetActivated([in] Windows.ApplicationModel.Activation.ShareTargetActivatedEventArgs *args);
//        HRESULT OnFileOpenPickerActivated([in] Windows.ApplicationModel.Activation.FileOpenPickerActivatedEventArgs *args);
//        HRESULT OnFileSavePickerActivated([in] Windows.ApplicationModel.Activation.FileSavePickerActivatedEventArgs *args);
//        HRESULT OnCachedFileUpdaterActivated([in] Windows.ApplicationModel.Activation.CachedFileUpdaterActivatedEventArgs *args);
//        HRESULT OnWindowCreated([in] Windows.ApplicationModel.WindowCreatedEventArgs *args);
//    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.Application),
        uuid(06499997-f7b4-45fe-b763-7577d1d3cb4a)
    ]
    interface IApplicationStatics : IInspectable
    {
        [propget] HRESULT Current([out, retval] Windows.UI.Xaml.Application **value);
        HRESULT Start([in] Windows.UI.Xaml.ApplicationInitializationCallback *callback);
        [overload("LoadComponent")] HRESULT LoadComponent([in] IInspectable *component, [in] Windows.Foundation.Uri *resource_locator);
        [overload("LoadComponent")] HRESULT LoadComponentWithResourceLocation([in] IInspectable *component, [in] Windows.Foundation.Uri *resource_locator, [in] Windows.UI.Xaml.Controls.Primitives.ComponentResourceLocation component_resource_location);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.BindingFailedEventArgs),
        uuid(32c1d013-4dbd-446d-bbb8-0de35048a449)
    ]
    interface IBindingFailedEventArgs : IInspectable
    {
        [propget] HRESULT Message([out, retval] HSTRING *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DataTemplateKey),
        uuid(873b6c28-cceb-4b61-86fa-b2cec39cc2fa)
    ]
    interface IDataTemplateKey : IInspectable
    {
        [propget] HRESULT DataType([out, retval] IInspectable **value);
        [propput] HRESULT DataType([in] IInspectable *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DataTemplateKey),
        uuid(e96b2959-d982-4152-91cb-de0e4dfd7693)
    ]
    interface IDataTemplateKeyFactory : IInspectable
    {
        HRESULT CreateInstance([in] IInspectable *base_interface, [out] IInspectable **inner_interface, [out, retval] Windows.UI.Xaml.DataTemplateKey **value);
        HRESULT CreateInstanceWithType([in] IInspectable *data_type, [in] IInspectable *base_interface, [out] IInspectable **inner_interface, [out, retval] Windows.UI.Xaml.DataTemplateKey **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DebugSettings),
    ]
    interface IDebugSettings : IInspectable
    {
        [propget] HRESULT EnableFrameRateCounter([out, retval] boolean *value);
        [propput] HRESULT EnableFrameRateCounter([in] boolean value);
        [propget] HRESULT IsBindingTracingEnabled([out, retval] boolean *value);
        [propput] HRESULT IsBindingTracingEnabled([in] boolean value);
        [propget] HRESULT IsOverdrawHeatMapEnabled([out, retval] boolean *value);
        [propput] HRESULT IsOverdrawHeatMapEnabled([in] boolean value);
        [eventadd] HRESULT BindingFailed([in] Windows.UI.Xaml.BindingFailedEventHandler *handler, [out, retval] EventRegistrationToken *cookie);
        [eventremove] HRESULT BindingFailed([in] EventRegistrationToken cookie);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DependencyObject),
        uuid(5c526665-f60e-4912-af59-5fe0680f089d)
    ]
    interface IDependencyObject : IInspectable
    {
        HRESULT GetValue([in] Windows.UI.Xaml.DependencyProperty *dp, [out, retval] IInspectable **result);
        HRESULT SetValue([in] Windows.UI.Xaml.DependencyProperty *dp, [in] IInspectable *value);
        HRESULT ClearValue([in] Windows.UI.Xaml.DependencyProperty *dp);
        HRESULT ReadLocalValue([in] Windows.UI.Xaml.DependencyProperty *dp, [out, retval] IInspectable **result);
        HRESULT GetAnimationBaseValue([in] Windows.UI.Xaml.DependencyProperty *dp, [out, retval] IInspectable **result);
        [propget] HRESULT Dispatcher([out, retval] Windows.UI.Core.CoreDispatcher **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DependencyObject),
        uuid(29fed85d-3d22-43a1-add0-17027c08b212)
    ]
    interface IDependencyObject2 : IInspectable
    {
        HRESULT RegisterPropertyChangedCallback([in] Windows.UI.Xaml.DependencyProperty *dp, [in] Windows.UI.Xaml.DependencyPropertyChangedCallback *callback, [out, retval] INT64 *result);
        HRESULT UnregisterPropertyChangedCallback([in] Windows.UI.Xaml.DependencyProperty *dp, [in] INT64 token);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DependencyObject),
        uuid(9a03af92-7d8a-4937-884f-ecf34fe02acb)
    ]
    interface IDependencyObjectFactory : IInspectable
    {
        HRESULT CreateInstance([in] IInspectable *base_interface, [out] IInspectable **inner_interface, [out, retval] Windows.UI.Xaml.DependencyObject **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DependencyProperty),
        uuid(85b13970-9bc4-4e96-acf1-30c8fd3d55c8)
    ]
    interface IDependencyProperty : IInspectable
    {
        HRESULT GetMetadata([in] Windows.UI.Xaml.Interop.TypeName type, [out, retval] Windows.UI.Xaml.PropertyMetadata **result);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DependencyPropertyChangedEventArgs),
        uuid(81212c2b-24d0-4957-abc3-224470a93a4e)
    ]
    interface IDependencyPropertyChangedEventArgs : IInspectable
    {
        [propget] HRESULT Property([out, retval] Windows.UI.Xaml.DependencyProperty **value);
        [propget] HRESULT OldValue([out, retval] IInspectable **value);
        [propget] HRESULT NewValue([out, retval] IInspectable **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.DependencyProperty),
        uuid(49e5f28f-8259-4d5c-aae0-83d56dbb68d9)
    ]
    interface IDependencyPropertyStatics : IInspectable
    {
        [propget] HRESULT UnsetValue([out, retval] IInspectable **value);
        HRESULT Register([in] HSTRING name, [in] Windows.UI.Xaml.Interop.TypeName property_type, [in] Windows.UI.Xaml.Interop.TypeName owner_type, [in] Windows.UI.Xaml.PropertyMetadata *type_metadata, [out, retval] Windows.UI.Xaml.DependencyProperty **result);
        HRESULT RegisterAttached([in] HSTRING name, [in] Windows.UI.Xaml.Interop.TypeName property_type, [in] Windows.UI.Xaml.Interop.TypeName owner_type, [in] Windows.UI.Xaml.PropertyMetadata *default_metadata, [out, retval] Windows.UI.Xaml.DependencyProperty **result);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.PropertyMetadata),
        uuid(814ef30d-8d18-448a-8644-f2cb51e70380)
    ]
    interface IPropertyMetadata : IInspectable
    {
        [propget] HRESULT DefaultValue([out, retval] IInspectable **value);
        [propget] HRESULT CreateDefaultValueCallback([out, retval] Windows.UI.Xaml.CreateDefaultValueCallback **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.PropertyMetadata),
        uuid(c1b81cc0-57cd-4f2f-b0a9-e1801b28f76b)
    ]
    interface IPropertyMetadataFactory : IInspectable
    {
        HRESULT CreateInstanceWithDefaultValue([in] IInspectable *default_value, [in] IInspectable *base_interface, [out] IInspectable **inner_interface, [out, retval] Windows.UI.Xaml.PropertyMetadata **value);
        HRESULT CreateInstanceWithDefaultValueAndCallback([in] IInspectable *default_value, [in] Windows.UI.Xaml.PropertyChangedCallback *property_changed_callback, [in] IInspectable* base_interface, [out] IInspectable **inner_interface, [out, retval] Windows.UI.Xaml.PropertyMetadata **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.PropertyMetadata),
        uuid(3b01077a-6e06-45e9-8b5c-af243458c062)
    ]
    interface IPropertyMetadataStatics : IInspectable
    {
        [default_overload] [overload("Create")] HRESULT CreateWithDefaultValue([in] IInspectable *default_value, [out, retval] Windows.UI.Xaml.PropertyMetadata **result);
        [default_overload] [overload("Create")] HRESULT CreateWithDefaultValueAndCallback([in] IInspectable *default_value, [in] Windows.UI.Xaml.PropertyChangedCallback *property_changed_callback, [out, retval] Windows.UI.Xaml.PropertyMetadata **result);
        [overload("Create")] HRESULT CreateWithFactory([in] Windows.UI.Xaml.CreateDefaultValueCallback *create_default_value_callback, [out, retval] Windows.UI.Xaml.PropertyMetadata **result);
        [overload("Create")] HRESULT CreateWithFactoryAndCallback([in] Windows.UI.Xaml.CreateDefaultValueCallback *create_default_value_callback, [in] Windows.UI.Xaml.PropertyChangedCallback *property_changed_callback, [out, retval] Windows.UI.Xaml.PropertyMetadata **result);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.ResourceDictionary),
        uuid(c1ea4f24-d6de-4191-8e3a-f48601f7489c)
    ]
    interface IResourceDictionary : IInspectable
    {
        [propget] HRESULT Source([out, retval] Windows.Foundation.Uri **value);
        [propput] HRESULT Source([in] Windows.Foundation.Uri *value);
        [propget] HRESULT MergedDictionaries([out, retval] Windows.Foundation.Collections.IVector<Windows.UI.Xaml.ResourceDictionary *> **value);
        [propget] HRESULT ThemeDictionaries([out, retval] Windows.Foundation.Collections.IMap<IInspectable *, IInspectable *> **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.UI.Xaml.UnhandledExceptionEventArgs),
        uuid(7230269c-054e-4cf3-86c5-be90eb6863d5)
    ]
    interface IUnhandledExceptionEventArgs : IInspectable
    {
        [propget] HRESULT Exception([out, retval] HRESULT *value);
        [propget] HRESULT Message([out, retval] HSTRING *value);
        [propget] HRESULT Handled([out, retval] boolean *value);
        [propput] HRESULT Handled([in] boolean value);
    }

    [
        composable(Windows.UI.Xaml.IApplicationFactory, public, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        static(Windows.UI.Xaml.IApplicationStatics, Windows.Foundation.UniversalApiContract, 1.0),
        threading(both)
    ]
    runtimeclass Application
    {
        [default] interface Windows.UI.Xaml.IApplication;
        /* interface Windows.UI.Xaml.IApplicationOverrides; */
        /* [contract(Windows.Foundation.UniversalApiContract, 3.0)] interface Windows.UI.Xaml.IApplication2; */
        /* [contract(Windows.Foundation.UniversalApiContract, 4.0)] interface Windows.UI.Xaml.IApplication3; */
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass ApplicationInitializationCallbackParams
    {
        [default] interface Windows.UI.Xaml.IApplicationInitializationCallbackParams;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass BindingFailedEventArgs
    {
        [default] interface Windows.UI.Xaml.IBindingFailedEventArgs;
    }

    [
        composable(Windows.UI.Xaml.IDataTemplateKeyFactory, public, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass DataTemplateKey
    {
        [default] interface Windows.UI.Xaml.IDataTemplateKey;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass DebugSettings
    {
        [default] interface Windows.UI.Xaml.IDebugSettings;
        /* [contract(Windows.Foundation.UniversalApiContract, 7.0)] interface Windows.UI.Xaml.IDebugSettings2; */
    }

    [
        composable(Windows.UI.Xaml.IDependencyObjectFactory, protected, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass DependencyObject
    {
        [default] interface Windows.UI.Xaml.IDependencyObject;
        [contract(Windows.Foundation.UniversalApiContract, 1.0)] interface Windows.UI.Xaml.IDependencyObject2;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        static(Windows.UI.Xaml.IDependencyPropertyStatics, Windows.Foundation.UniversalApiContract, 1.0),
        threading(both)
    ]
    runtimeclass DependencyProperty
    {
        [default] interface Windows.UI.Xaml.IDependencyProperty;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass DependencyPropertyChangedEventArgs
    {
        [default] interface Windows.UI.Xaml.IDependencyPropertyChangedEventArgs;
    }

    [
        composable(Windows.UI.Xaml.IPropertyMetadataFactory, public, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        static(Windows.UI.Xaml.IPropertyMetadataStatics, Windows.Foundation.UniversalApiContract, 1.0),
        threading(both)
    ]
    runtimeclass PropertyMetadata
    {
        [default] interface Windows.UI.Xaml.IPropertyMetadata;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass ResourceDictionary : Windows.UI.Xaml.DependencyObject
    {
        [default] interface Windows.UI.Xaml.IResourceDictionary;
        /* interface Windows.Foundation.Collections.IMap<IInspectable *, IInspectable *>; */
        /* interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<IInspectable *, IInspectable *> *>; */
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass UnhandledExceptionEventArgs
    {
        [default] interface Windows.UI.Xaml.IUnhandledExceptionEventArgs;
    }
}
